# Generated by Django 3.1.3 on 2020-11-28 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sber_mail', '0002_auto_20201128_0011'),
    ]

    operations = [
        migrations.AddField(
            model_name='sbermail',
            name='priority',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sbermail',
            name='tags',
            field=models.TextField(default='lol'),
            preserve_default=False,
        ),
    ]
