# Generated by Django 3.1.3 on 2020-11-28 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sber_mail', '0003_auto_20201128_1305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sbermail',
            name='priority',
            field=models.CharField(max_length=1),
        ),
    ]
