# Generated by Django 3.1.3 on 2020-11-28 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sber_mail', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sbermail',
            name='mail_id',
        ),
        migrations.AddField(
            model_name='sbermail',
            name='seen',
            field=models.BooleanField(default=False),
        ),
    ]
